### PR TITLE
[WIP] Open from bytes slice

### LINKED ISSUE #13: Question, open compressed file
Hello, and thank you for creating this lib! :100: 

As there is no documentation to refer to, I see that I can (and do) open a file using `netcdf::open`, but is there a way to open from a buffer / various compressed formats? Right now I would like to have the files saved in gzip format, but unsure how to load them directly into `netcdf`

### PR DESCRIPTION
**Pull request by milesgranger**
Will close #13 

Disclosure, I'm _very_ new to interfacing Rust with C. 

With that said, I've gotten as far as I can, and so far I see it, the test I've added should pass, but I get an error code `2` back from the [nc_open_mem](https://www.unidata.ucar.edu/software/netcdf/docs/group__datasets.html#ga91027f1f0530f8ce54d4072ed10be4c1) as suggested in the original issue. So I must be doing a silly thing here and there. 

Willing to go further with a few hints. :+1:

### CODE REVIEW

**Comment by milesgranger** [comment]
Hi @mhiley & @evomassiny 

Please excuse the code, for now, I'll polish it up, but I need some clarification on something first:

I've got it to pass the tests using the `net_open_mem` as described in the issue #13; only I had to copy over the function from the `netcdf_mem.h` file into `netcdf.h` and then add to the `netcdf_bindings.rs` as there was no `build.rs` or otherwise, so I'm not sure how it was created in the first place aside from using `bindgen` (and thus why it fails on Travis.. but that's another problem I guess)

Anyways, it appears that the file _needs_ to be on the FS with a valid path to it. Does this not defeat the purpose of `net_open_mem`? ie. if I change the required path to something non-existant it complains there is no such file or directory; even though the contents of the file is in the buffer.

In practice, I'll be receiving netCDF files in raw bytes and need to load them up without ever writing them out. Am I missing something silly here? 

Really want to get this feature merged in, so any help is appreciated and will be

**Comment by mhiley** [comment]
Hi @milesgranger , sorry again for another long delay on this - hope this haven't lost your interest yet. On the bright side, I've got a dev environment up and running again for this repo and am getting reimmersed, so hopefully we can get things moving more quickly now.

Ok regarding the Travis build failure, I believe the cause is that the Travis build was running Ubuntu 14.04 (Trusty) which was stuck on netcdf 4.1.3. The `nc_open_mem` function was new in netcdf 4.4.0 (source: https://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-4-0) so things failed.

I upgraded the `.travis.yml` file on master to run Ubuntu 16.04 (Xenial) which gets us to netcdf 4.4.0.

So, I think if you merge master into your branch, the build issue in Travis should be fixed.

Once we confirm that, I can dig more into the issue about not being able to load from memory without writing the file to disk. Not sure what's going on there - the netcdf docs suggest the "path" argument is "only used to set the dataset name" so it's odd that it would fail if there's no file at that path.

**Comment by mhiley** [comment]
@milesgranger update to above:

Check out: https://github.com/Unidata/netcdf-c/issues/394

They fixed a bug causing "no such file or directory" with `nc_open_mem` .. that was merged into `netcdf-c` master on May 5, 2017. Looking at the netcdf-c release history, I think that means we need at least netcdf 4.5.0. (As I mentioned above, once you merge in latest `rust-netcdf` master, the travis build is only on 4.4.0).

What version of netcdf are you building against? If you upgrade to at least `4.5.0` does that fix your problem?

**Comment by milesgranger** [comment]
Hi @mhiley you're right, works after rebasing on master, but will still fail if I put in a non-existant path as I am indeed working with netcdf 4.4.1. I'll try and set aside some time later to get 4.5 going and see how it goes. Thanks!

**Comment by milesgranger** [comment]
@mhiley 
Sorry for the delay, I've been messing with compiling 4.5 from source, but having a heck of a time. Do you think you could either update the existing repo's Dockerfile or add another which does this, of which I could use as a template?

**Pull request closed without merging**
