### PR TITLE
subsetted writes

### PR DESCRIPTION
**Pull request by evomassiny**
Hello,

I've implemented subsetted *writes* using [those functions](https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-c/nc_005fput_005fvara_005f-type.html) from the libnetCDF library. 
A user should now be able to:
* open a file in read/write mode using the ['append' function](https://github.com/evomassiny/rust-netcdf/blob/develop/src/file.rs#L45),
* write a single value into a netCDF variable at a specific index using [put_value_at](https://github.com/evomassiny/rust-netcdf/blob/develop/src/variable.rs#L443),
* write multiple values at a specific index using [put_values_at](https://github.com/evomassiny/rust-netcdf/blob/develop/src/variable.rs#L448)

I've also updated the documentation and the units tests accordingly,
I would love to see those changes merged, please tell me if anything is wrong with those.

Thanks for your time.

### CODE REVIEW

**Comment by evomassiny** [comment]
Travis is yelling at me, I need to fix that first :/
Sorry.

**Comment by evomassiny** [comment]
Hello again, 

It turns out that travis was yelling for 2 different reasons:
* opening a file in read/write mode, closing it and then re-opening it in read mode triggers this error "H5F_open(): unable to truncate a file which is already open", which apparently is [supposed to happen](https://github.com/h5py/h5py/issues/332), a quick fix was to re-open it in read/write mode.
* the use of **extern static** variables now requires an unsafe block, which means that even the current version can't be built using the nightly and betâ version of rustc :/ (see this [issue](https://github.com/rust-lang/rust/issues/35112) )

I will try to refactor the **netcdf-sys** crate in order to get it working with the future versions of rust (and the current betâ and nightly version), but this problem is not related to this pull request, that's why I still wish to merge this PR, if you're OK with it.

Thanks for your time.

**Comment by evomassiny** [comment]
Hello again,

I managed to refactor the netcdf-sys module to avoid the use of **extern static** bindings ([which caused the build failure](https://github.com/rust-lang/rust/issues/35112) on the beta and nightly channels).
I've basically replaced all the constants of "netcdf-sys/src/ncconst.c" by rust constants, directly generated using a newer version of bindgen. This also simplify the build of the netcdf-sys crate (because we don't need to generate C constant, and their rust bindings).

The whole crate now compile without warnings, and all tests are successful using all rust versions :)

Thanks for your time.

**Comment by mhiley** [comment]
This is great, thanks so much!

**Pull request merged**
