### PR TITLE
Change header name in netcdf-sys

### PR DESCRIPTION
**Pull request by evomassiny**
Hello,

I wasn't able to build netcdf-sys without renaming  "netcdf_v4.3.3.1.h" to "netcdf.h", and without changing the gcc call in "netcdf-sys/build.rs" (to include "netcdf.h").
I've made a fork that I could compile, it does work but some units tests fail.
I assume it's caused by my version of libnetcdf-dev. (1:4.1.3-7ubuntu2 amd64).

I'm both new to rust and to the netcdf file format :S, I really hope I'm not wasting your time.
Best regards, 

evomassiny

### CODE REVIEW

**Comment by mhiley** [comment]
Hello, thanks for the pull request!

I bet your suspicion about netcdf versioning issues is correct; I really only ever tested this on one netcdf version. I'd like to look into these issues myself and also investigate why the CI builds are failing after d841167 before accepting your pull request though.. I'll try to check it out this weekend!

**Comment by evomassiny** [comment]
Hello again,

After removing the "nc_write" flag in the "nc_create" call, ( src/file.rs ) every test succeed :) (commit [https://github.com/mhiley/rust-netcdf/pull/3/commits/aa7f785e9e7d9ea02e30e1232f36db60f2a9192a] ).
Thanks for your time

**Comment by mhiley** [comment]
Right, I believe the unit tests succeed for you, but something in commit d841167 caused the Travis Continous Integration builds to start failing. (That's the little red X's next to the commit hashes in the pull request). See for example:

https://travis-ci.org/mhiley/rust-netcdf/builds/162049536

The log message from CI builds aren't very helpful, unfortunately. I'll try to dig in more this weekend.

**Comment by mhiley** [comment]
Oh and by the way, what Rust and Cargo versions are you running?

**Comment by evomassiny** [comment]
I didn't knew about Travis (I'm quite new to github) :/, i will look into it.
About my config :  i'm using rustc 1.11.0 (9b21dcd6a 2016-08-15) and cargo 0.12.0-nightly (6b98d1f 2016-07-04).

**Comment by evomassiny** [comment]
Hello,

After 7 month, I've decided to give it another try :)
I manage to get the Travis build system to work by modifying the **travis.yml** file, I've basically adapted the one from the python netCDF4 [module repository](https://github.com/Unidata/netcdf4-python/blob/master/.travis.yml).
The build works for the stable, beta and nightly version of rust.
Thanks for your time.

**Comment by evomassiny** [comment]
Hello again,
Have you had time to look at it ?
I would like to do further improvement to the "Variable" struct, so the user could get its value 
as an [ndarray](https://github.com/bluss/rust-ndarray), if it's ok with you.

**Comment by mhiley** [comment]
This is great, sorry I missed your comment a few weeks ago and thanks for getting digging into it and getting the Travis build working again!

**Pull request merged**
